# A dictionary of the clusters/environments that we can onboard applications into
clusters:
  # Name of the cluster/environment
  tools:
    # Master endpoint of the cluster (this must match what is defined for the cluster in ArgoCD)
    server: "https://kubernetes.default.svc"
    # Name of the cluster (this must match what is defined for the cluster in ArgoCD)
    name: "in-cluster"
  minikube: 
    server: "https://192.168.49.2:8443"
    name: "minikube"

# A list of the projects that will be created in ArgoCD, a project will have multiple applications defined under it
projects:
# This is the name that will be used directly when creating the ArgoCD Project
- name: "global"
  # This is the description that will be used directly when creating the ArgoCD Project
  description: "Project for apps which are deployed globally for clusters"
  # A list of clusterResourceWhitelist items for this project, allows applications in this project to create cluster level resources specified
  # By default we do not allow applications to create any cluster level resources (only namespaced resources)
  # OPTIONAL
  clusterResourceWhitelistOverrides:
  - group: ''
    kind: Namespace
  # Override the allowed namespaces for applications
  # By default all namespaces for applications must begin with the name of the project
  # If you want applications in this project be able to deploy to any namespace the value must be literal "'*'"
  # OPTIONAL
  namespaceOverride: "'*'"
  # A list of the applications i.e. a link from source to destinations
  # An ArgoCD application is created per application environment an application with no environments specified will not have any effect
  applications:
    # This name is used as part of the ArgoCD application name, which will be of the format:
    # {project.name}-{application.name}-{environment.name}
  - name: "namespaces"
    # By default we look for environment folders in the root of the repository e.g. /dev /qal
    # This optional key allows you put application environment definitions into folders e.g. /pathPrefix/dev /pathPrefix/qal
    # OPTIONAL
    pathPrefix: "global-applications/namespaces"
    # Specifies the repository that contains the deployment resources for this application
    # APPLICATION SPECIFIC NOTE: The namespaces "application" depends on this values.yaml file, so it co-exists in this repo
    repoURL: "https://github.com/trevgall/argocd-lab-apps.git"
    # List of environments/clusters for which an ArgoCD application (and namespace) will be created
    environments:
    - name: tools

# - name: "infra"
#   description: "Project for Shared Infrastructure Services"
#   clusterResourceWhitelistOverrides:
#   - group: "rbac.authorization.k8s.io"
#     kind: ClusterRole
#   - group: "rbac.authorization.k8s.io"
#     kind: ClusterRoleBinding
#   - group: "apiextensions.k8s.io"
#     kind: CustomResourceDefinition
#   - group: "admissionregistration.k8s.io"
#     kind: ValidatingWebhookConfiguration
#   - group: "admissionregistration.k8s.io"
#     kind: MutatingWebhookConfiguration
#   - group: "cert-manager.io"
#     kind: ClusterIssuer
#   - group: kyverno.io
#     kind: ClusterPolicy
#   namespaceOverride: "'*'"
#   applications:
#   - name: "external-dns"
#     pathPrefix: "external-dns"
#     repoURL: "https://github.com/ncr-digital-banking/dbk-sre-tools-cluster-infra-lab-apps.git"
#     namespaceOverride: infra-external-dns
#     environments:
#     - name: tools
#   - name: "ingress-nginx"
#     pathPrefix: "ingress-nginx"
#     repoURL: "https://github.com/ncr-digital-banking/dbk-sre-tools-cluster-infra-lab-apps.git"
#     namespaceOverride: infra-ingress-nginx
#     environments:
#     - name: tools
#   - name: "argocd-ingress"
#     pathPrefix: "argocd-ingress"
#     repoURL: "https://github.com/ncr-digital-banking/dbk-sre-tools-cluster-infra-lab-apps.git"
#     namespaceOverride: argocd
#     dontCreateOverriddenNamespace: true
#     environments:
#     - name: toolsncr-digital-banking/sre-cicd/dbk-sre-argocd-lab-apps
#   - name: "kyverno"
#     pathPrefix: "kyverno"
#     repoURL: "https://github.com/ncr-digital-banking/dbk-sre-tools-cluster-infra-lab-apps.git"
#     namespaceOverride: infra-kyverno
#     environments:
#     - name: tools

- name: "guestbook"
  description: "ArgoCD example guestbook app"
  applications:
  - name: "guestbook"
    pathPrefix: "guestbook"
    repoURL: "https://github.com/trevgall/argocd-example-apps.git"
    environments:
    - name: minikube

- name: "microservices"
  description: "Google Microservices Online Boutique"
  namespaceOverride: "'*'"
  applications: 
  - name: "ads"
    pathPrefix: "ads"
    repoURL: "https://github.com/trevgall/google-microservices-demo.git"
    namespaceOverride: microservices
    environments:
    - name: minikube